# Generated by Django 3.2.7 on 2022-01-20 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tags',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to=settings.AUTH_USER_MODEL)),
                ('news_liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_liked', to='news.news')),
            ],
            options={
                'verbose_name': 'Лайк новостя',
                'verbose_name_plural': 'Лайкл новостей',
                'ordering': ('-news_liked',),
            },
        ),
        migrations.CreateModel(
            name='NewsComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('news_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.news')),
            ],
            options={
                'verbose_name': 'Комент новостя',
                'verbose_name_plural': 'Коменты новостей',
                'ordering': ('-created',),
            },
        ),
    ]
