# Generated by Django 3.2.7 on 2022-01-24 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsimage_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomment',
            name='news_comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comment', to='news.news'),
        ),
    ]
