# Generated by Django 3.2.7 on 2022-01-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20220124_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='url',
        ),
    ]
