# Generated by Django 3.2.7 on 2022-02-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_advert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advert',
            options={'verbose_name': 'Реклама', 'verbose_name_plural': 'Рекламы'},
        ),
        migrations.AddField(
            model_name='advert',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-01-01 01:01'),
            preserve_default=False,
        ),
    ]
